# Generated by Django 3.0.7 on 2020-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200716_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fax_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
