# Generated by Django 3.0.7 on 2020-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200630_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='emails',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
