# Generated by Django 3.0.7 on 2020-07-19 21:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20200720_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firm',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
