# Generated by Django 3.0.7 on 2020-09-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20200902_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='favourite',
        ),
    ]
